# -*- coding: utf-8 -*-
"""movies.02

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EVa-V1qKjnCDJovkhlWZZGOEdBHmU38i
"""

import pandas as pd
df=pd.read_csv('movies.2.csv')
print(df.head(10))

#check for missing values
print(df.isnull().sum())

#Remove missing values
df_cleaned=df.dropna()
print(df_cleaned)

#Forward Fill
df.ffill(inplace=True)
print(df)

#Backward Fill
df.bfill(inplace=True)
print(df)

#Remove Duplicates
df.drop_duplicates(inplace=True)
print(df)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#Example DataFrame
df=pd.DataFrame({'Movie Name':['Toy Story','Jumanji','Grumpier Old Men','Waiting to Exhale'],
  'Genre':['Fantasy','Fantasy','Comedy','Comedy']})

plt.figure(figsize=(8,4))
sns.countplot(data=df,x='Genre',palette='muted')
plt.title('Number of Movies by Genre')
plt.show()

plt.figure(figsize=(8,4))
sns.countplot(data=df,x='Movie Name',palette='muted')
plt.title('Number of Movies by Genre')
plt.show()